Import dependencies

In [43]:
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# load dataset to pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first five rows of dataset
credit_card_data.head()

   Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  1.378155  ... -0.189115  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  0.448154  ...  0.125895 -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  0.379780  ... -0.139097 -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993 -0.863291  ... -0.221929  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  0.403034  ...  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [ ]:
# last five rows
credit_card_data.tail()

            Time         V1         V2        V3  ...       V27       V28  Amount  Class
284802  172786.0 -11.881118  10.071785 -9.834783  ...  0.943651  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  2.035030  ...  0.068472 -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254 -3.249640  ...  0.004455 -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  0.702510  ...  0.108821  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  0.703337  ... -0.002415  0.013649  217.00      0

[5 rows x 31 columns]

In [ ]:
#dataset info
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [ ]:
#check the number of missing values
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
#distribution od legit transaction and fraud transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

the dataset is highly unbalanced
0--> legit
1--> fraud

In [ ]:
#separate the data for analysis
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

               Time        V1        V2        V3  ...       V26       V27       V28      Amount
Class                                              ...
0      94838.202258  0.008258 -0.006271  0.012171  ... -0.000089 -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778 -7.033281  ...  0.051648  0.170575  0.075667  122.211321

[2 rows x 30 columns]

under-sampling

build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

In [ ]:
legit_sample=legit.sample(n=492)

concatenate two dataframes

In [ ]:
new_dataset=pd.concat([legit_sample,fraud], axis=0)

In [ ]:
new_dataset.head()

            Time        V1        V2        V3  ...       V27       V28  Amount  Class
134021   80612.0 -1.335036  1.695224  0.542551  ...  0.108961  0.009412   15.98      0
128756   78828.0  1.398769 -1.225595  1.115228  ...  0.087880  0.022429    5.00      0
100791   67624.0 -0.865122 -0.280540  3.136713  ...  0.353833  0.115797    1.00      0
33833    37406.0 -0.815373  0.570236  1.231694  ...  0.470646  0.124642  106.42      0
210188  137876.0 -0.261382 -0.477635  0.934027  ...  0.196567  0.001305   39.00      0

[5 rows x 31 columns]

In [ ]:
new_dataset.tail()

            Time        V1        V2        V3  ...       V27       V28  Amount  Class
279863  169142.0 -1.927883  1.125653 -4.518331  ...  0.292680  0.147968  390.00      1
280143  169347.0  1.378559  1.289381 -5.004247  ...  0.389152  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366 -2.213700  ...  0.385107  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864 -5.399730  ...  0.884876 -0.253700  245.00      1
281674  170348.0  1.991976  0.158476 -2.583441  ...  0.002988 -0.015309   42.53      1

[5 rows x 31 columns]

In [ ]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

               Time        V1        V2        V3  ...       V26       V27       V28      Amount
Class                                              ...
0      93374.890244  0.070317  0.047863  0.063874  ...  0.005944  0.026936  0.003409   75.569939
1      80746.806911 -4.771948  3.623778 -7.033281  ...  0.051648  0.170575  0.075667  122.211321

[2 rows x 30 columns]

split the data into feature and target

In [ ]:
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [ ]:
print(X)

            Time        V1        V2        V3  ...       V26       V27       V28  Amount
134021   80612.0 -1.335036  1.695224  0.542551  ...  0.052315  0.108961  0.009412   15.98
128756   78828.0  1.398769 -1.225595  1.115228  ... -0.094338  0.087880  0.022429    5.00
100791   67624.0 -0.865122 -0.280540  3.136713  ... -0.109593  0.353833  0.115797    1.00
33833    37406.0 -0.815373  0.570236  1.231694  ...  0.461661  0.470646  0.124642  106.42
210188  137876.0 -0.261382 -0.477635  0.934027  ... -0.150951  0.196567  0.001305   39.00
...          ...       ...       ...       ...  ...       ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653 -4.518331  ...  0.788395  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381 -5.004247  ...  0.739467  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366 -2.213700  ...  0.471111  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864 -5.399730  ...  0.606116  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476 -2.583441  ... -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [ ]:
print(Y)

134021    0
128756    0
100791    0
33833     0
210188    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

split data into training data and test data

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

LogisticRegression

In [ ]:
 model = LogisticRegression()

In [ ]:
#train the model with training data
model.fit(X_train,Y_train)
max_iter=100

Model Evalution

Accuracy Score

In [ ]:
#accuracy on train data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
print('Accuracy on training data: ',training_data_accuracy)

Accuracy on training data:  0.9555273189326556

In [ ]:
#accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
print('Accuracy score on Test Data: ',test_data_accuracy)

Accuracy score on Test Data:  0.9238578680203046

In [47]:
with open('model.pkl', 'wb') as file:
     pickle.dump(model,file)